language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install . --use-mirrors
  - pip install coveralls pep8 --use-mirrors
script:
  - coverage run --source=jelly setup.py nosetests
  - pep8
after_success:
  coveralls
